### ISSUE TITLE
problems with running commands and permissions

### ISSUE THREAD

**Issue by furious122** [Hempfest/Clans#7]
Hello, i am opening a server similar to smp earth and i was looking for a factions plugin, i stumbled across this one, as i added everything necesary and tested the plugin on the server with my friend ( version 1.16.5) we came across two problems, the first being everytime i tried to run a command as a operator it gave me the following message : ''An internal error occurred while attempting to perform this command''. Secondly my friend who was not a opperator was not able to even run a command. the list of plugins i use will be listed below =

AntiCombatLog
DeadChest
DropHeads
Dynmap
ImageMaps
Labyrinth
OnePlayerSleep
PixelTpa
UnlimitedAnvil
and hEssentialsClans

here is the error message =  World not found in configuration. Raid-shield will not work properly.

My server is opening Thursday if i could get a response ASAP that would be appreciated!

**Comment by Hempfest** [comment]
Hello, im terribly sorry to inconvenience but Clans free is undergoing a complete revamp, you can check on progress in our discord server! Were kind of dropping support for the current build, there were enough problems with it for it to be easier to remake instead of polish
